Add some safety check for converting the configuration

diff --git a/debian/knot.preinst b/debian/knot.preinst
--- a/debian/knot.preinst
+++ b/debian/knot.preinst
@@ -3,6 +3,16 @@ set -e
 
 dpkg-maintscript-helper rm_conffile /etc/default/knot 1.3.0~rc3-2~ -- "$@"
 
+# Doesn't work since we have only one version of knot-libs
+#
+#if [ "$1" = "upgrade" ]; then
+#    if ! /usr/sbin/knotc checkconf >/dev/null 2>/dev/null; then
+#	echo "ERROR: Your /etc/knot/knot.conf is not valid, aborting installation."
+#	/usr/sbin/knotc checkconf
+#	exit 1
+#    fi
+#fi
+
 #DEBHELPER#
 
 exit 0
